### PR TITLE
Support both DLC and vanilla

### PR DESCRIPTION
**Pull request by TheLurkingCat**
The archived_version's dll is taken from current steam version
The DLC version's dll is taken from master branch
Just add another folder to suppport those three version (DLC. DLC_VANILLA, VANILLA)

### CODE REVIEW

**Comment by Pholith** [comment]
I don't want my mods to contain different version files. It adds unnecessary complexity. 

Currently, the mod is compatible with both versions. The version published on github will be published on Steam when "The big Merge update" will be also distributed with the vanilla, the mod will be then always compatible with the DLC, active or not.

**Comment by TheLurkingCat** [comment]
Current version on steam is mark as Outdated in DLC.

**Comment by Pholith** [comment]
Why doesn't anyone tell me in comments or make an issue...
This must be due to mod_info.yaml. Thanks I'll change that as soon as possible.

**Comment by TheLurkingCat** [comment]
DLC and base vanilla cannot use a single dll, since the harmony version is not compatible.
So basically it needs at least 2 dlls

When base vanilla merged you can simply delete the archive_version folder.

**Comment by Pholith** [comment]
Both versions of the game actually use Harmony 1.0, and DLC version can handle 2.0 with an additional parameter. When this changed ? https://forums.kleientertainment.com/forums/topic/130712-oni-is-upgrading-to-harmony-20/ 
If it doen't work, I may reopen your pull waiting the big merge

**Comment by TheLurkingCat** [comment]
This link says DLC will ship with harmony 2, so it needs to change some code and recompile in order to work.

I guess setting API Version is just indicating you have updated your mod.

By the way, staticID field should be put in mod.yaml, not mod_info.yaml

**Comment by Pholith** [comment]
Hey, I choiced to merge your commit until the base game is merged.
I know this mod is very important for the community. Thanks for your contribution and especially your help on the DLC.

**Pull request merged**
